Fix build with GCC 13 (missing <cstdint> include)
When building scipy, one gets:
```
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:304:17: error: ‘uint8_t’ was not declared in this scope
  304 | SCALAR_COMBINER(uint8_t)
      |                 ^~~~~~~
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:300:21: note: in definition of macro ‘SCALAR_COMBINER’
  300 |   struct __combined<Type, Type> {                                              \
      |                     ^~~~
/usr/lib/python3.10/site-packages/pythran/pythonic/include/types/combined.hpp:5:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include "pythonic/include/types/traits.hpp"
  +++ |+#include <cstdint>
```

Bug: https://bugs.gentoo.org/878527