Import analyses from their defining modules
Five analyses import other analyses from the `pythran.analyses` package,
while `pythran/analyses/__init__.py` imports those five modules. This only
works because of the order of the imports in `__init__.py`. For example,
moving `from .fixed_size_list import FixedSizeList` to the top of it gives:

    ImportError: cannot import name 'Aliases' from partially initialized
    module 'pythran.analyses' (most likely due to a circular import)

Importing from the defining modules, as the other analyses already do,
removes the dependency on the import order.

    $ uncycle --baseline ../master/pythran pythran
    dependencies to remove decreased from 5 to 0